### ISSUE TITLE
Hash speed not shown in table anymore.

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#18]
Miners hash speed used to be shown in Running/Idle section. This is now empty.

Might be due to the recurring following error:

```
Mining is currently profitable using the algorithms listed above. According to pool pricing information currently mining 5,96 EUR/day (7,91 - 2,05 EUR/day).
(Profitability limit: 2,00 EUR/day; Power cost 0,25 EUR/kW; 1 BTC = 12.090,88 EUR).


   Status: Running

 Speed Time spent mining           Launched Algorithm(s)  Profit Earning Command
 ----- -----------------           -------- ------------  ------ ------- -------
0  H/s 00 Days 00 Hours 00 Minutes Once     Nist5        5,95891 7,90683 \Bin\NVIDIA-KlausT818_CUDA91\ccminer.exe -a nist5 -o stratum+tcp://nist5.eu.nicehash.com:3340 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J.sloeber10 -p x -b 4281

>> TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."
PS>TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."

   Status: Idle

Speed Time spent mining           Launched Algorithm(s)  Profit Earning Command
----- -----------------           -------- ------------  ------ ------- -------
      00 Days 00 Hours 05 Minutes 2 Times  Lyra2z       3,43552 4,66802 \Bin\NVIDIA-Nanashi\ccminer.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u hapmine.sloeber10 -p x -b 4361
      00 Days 00 Hours 55 Minutes 25 Times Skunk        2,71574 4,54077 \Bin\NVIDIA-Nanashi\ccminer.exe -a skunk -o stratum+tcp://skunk.eu.nicehash.com:3362 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J.sloeber10 -p x -b 4361
      00 Days 01 Hours 40 Minutes 41 Times Nist5        0,00000 0,00000 \Bin\NVIDIA-KlausT818_CUDA91\ccminer.exe -a nist5 -o stratum+tcp://nist5.mine.zpool.ca:3833 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J -p sloeber10,c=BTC -b 4281
      00 Days 00 Hours 24 Minutes 7 Times  X17          2,65483 4,51915 \Bin\NVIDIA-KlausT818_CUDA91\ccminer.exe -a X17 -o stratum+tcp://x17.mine.zpool.ca:3737 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J -p sloeber10,c=BTC -b 4281
      00 Days 00 Hours 24 Minutes 7 Times  X17          2,86733 4,55666 \Bin\NVIDIA-SP\ccminer.exe -a x17 -o stratum+tcp://x17.mine.zpool.ca:3737 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J -p sloeber10,c=BTC -b 4441
      00 Days 00 Hours 06 Minutes 2 Times  Nist5        5,95135 7,90369 \Bin\NVIDIA-KlausT817_CUDA91\ccminer.exe -a nist5 -o stratum+tcp://nist5.eu.nicehash.com:3340 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J.sloeber10 -p x -b 4241
      00 Days 00 Hours 10 Minutes 4 Times  Lyra2z       2,24446 3,45394 \Bin\NVIDIA-ccminer-2.2.3-x64\ccminer-x64.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u hapmine.sloeber10 -p x -b 4081   --submit-stale
      00 Days 00 Hours 05 Minutes 2 Times  Skunk        0,00000 0,00000 \Bin\NVIDIA-ccminer-2.2.3\ccminer.exe -a skunk -o stratum+tcp://skunk.eu.nicehash.com:3362 -u 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb.multipoolminer -p x -b 4121   --submit-stale
      00 Days 00 Hours 05 Minutes 2 Times  Skunk        0,00000 0,00000 \Bin\NVIDIA-Nanashi\ccminer.exe -a skunk -o stratum+tcp://skunk.eu.nicehash.com:3362 -u 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb.multipoolminer -p x -b 4361
      00 Days 00 Hours 02 Minutes Once     Keccak       2,08489 4,07677 \Bin\NVIDIA-KlausT818_CUDA91\ccminer.exe -a keccak -o stratum+tcp://keccak.eu.nicehash.com:3338 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J.sloeber10 -p x -b 4281
      00 Days 00 Hours 05 Minutes 3 Times  Lyra2z       2,36968 3,59637 \Bin\NVIDIA-ccminer-2.2.3\ccminer.exe -a lyra2z -o stratum+tcp://europe.lyra2z-hub.miningpoolhub.com:17025 -u hapmine.sloeber10 -p x -b 4121   --submit-stale
      00 Days 00 Hours 48 Minutes 17 Times PHI          3,02085 4,86481 \Bin\NVIDIA-ccminer-2.2.3\ccminer.exe -a phi -o stratum+tcp://phi.mine.zpool.ca:8333 -u 14VMs2dR2QGFGerbGTRikNpeZK2VPSJA5J -p sloeber10,c=BTC -b 4121   --submit-stale


2018-01-02 14:23:23 INFO: Waiting for 120 seconds to start next run
```

**Comment by UselessGuru** [comment]
Should be fixed with https://github.com/UselessGuru/MultiPoolMiner/commit/ed84b3d794dfd5888cc010a06b97f68791ba6c60

If yes please close - thanks!

**Comment by hapklaar** [comment]
Now always shows 0 H/s

![image](https://user-images.githubusercontent.com/7703320/34504293-0f35d8c2-f01e-11e7-9840-776d1a3d06e0.png)

**Comment by hapklaar** [comment]
and can't connect to miners api anymore

2018-01-03 01:07:12 ERROR: Failed to connect to miner (DSTM).

**Comment by UselessGuru** [comment]
https://github.com/UselessGuru/MultiPoolMiner/commit/6ac73cd9fbfbdd690bc66972047100bd8c9a0408

**Comment by hapklaar** [comment]
Running shows 0 H/s
Idle shows no hash speed anymore

Running miner is being quit just to restart the same with different api port again

![image](https://user-images.githubusercontent.com/7703320/34505705-1b95c0b0-f027-11e7-9dde-e1b08c841550.png)

**Comment by UselessGuru** [comment]
> Running miner is being quit just to restart the same with different api port again

This is fixed this in my latest build. I'll upload soon.

**Comment by hapklaar** [comment]
Cool, please let me know when it's up.

**Comment by UselessGuru** [comment]
Should be fixed now. Please download the zip file and copy the contents over the old installation.

**Comment by hapklaar** [comment]
fixed in last update :)

**Comment by hapklaar** [comment]
damn... cheered too soon again. Issue still exists in current build

![image](https://user-images.githubusercontent.com/7703320/34592495-c25c5988-f1c4-11e7-8a8a-acd3224acfd5.png)

**Comment by UselessGuru** [comment]
Fixed now?

If yes please close - Thanks!

**Comment by platinum4** [comment]
For me, the speeds are all blank; not 0  H/s

**Comment by UselessGuru** [comment]
Cause found - will be fixed in the next release.

**Comment by UselessGuru** [comment]
Fixed. Please dwnload latest build

**Comment by platinum4** [comment]
Hell nawl this shit ain't fixed it ain't working on mines fool

And I get mine

**Comment by platinum4** [comment]
This doesn't work when `$DeviceSubTypes` = `$False`

**Comment by UselessGuru** [comment]
> This doesn't work when $DeviceSubTypes = $False

Well spottet, reason found. Will be fixed.
