### ISSUE TITLE
divide by zero error

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#19]
Only with 1 GPU installed I get the following error:

![image](https://user-images.githubusercontent.com/7703320/34506688-5042e074-f02f-11e7-8ce5-b5ecddd9fa14.png)

**Comment by UselessGuru** [comment]
A workaround:

https://github.com/UselessGuru/MultiPoolMiner/commit/5a1d96b50abb61c3a09146f0f6951c2c32f4adbd

Did you enable AMD or CPU mining?

**Comment by hapklaar** [comment]
No, just NVIDIA enabled.

**Comment by UselessGuru** [comment]
I've made a change to Include.psm1 that should fix this. Can you try and let me know? Thank you!

https://github.com/UselessGuru/MultiPoolMiner/commit/9c62d07e9765e024425be8eb4b0b56e45a8c6f31

**Comment by hapklaar** [comment]
fixed!

**Comment by hapklaar** [comment]
Hodl... when starting for the second time, after running ResetBenchmark.bat, error is back
[2018-01-04_17-19-43.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1603941/2018-01-04_17-19-43.txt)

**Comment by UselessGuru** [comment]
Should be fixed in latest zip. Please close if OK.

**Comment by hapklaar** [comment]
Fixed in #25 (I think)
